AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Ubuntu EC2 instance with KVS prerequisites'

Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id'
    Description: 'Ubuntu 22.04 LTS AMI from SSM Parameter Store'

Resources:
  EC2KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: aws-kvs-license-detection-key

  # KVS Stream
  KVSStream:
    Type: AWS::KinesisVideo::Stream
    Properties:
      Name: aws-kvs-license-detection-demo
      DataRetentionInHours: 24
      Tags:
        - Key: Name
          Value: aws-kvs-license-detection-demo

  # S3 Bucket
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub aws-kvs-license-detection-s3-${AWS::AccountId}-${AWS::Region}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t3.medium
      KeyName: !Ref EC2KeyPair
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      IamInstanceProfile: !Ref EC2InstanceProfile
      Tags:
        - Key: Name
          Value: aws-kvs-demo
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt update
          apt install -y cmake
          
          # Added build-essential installation
          sudo apt-get update
          sudo apt-get install -y build-essential
          
          sudo apt-get install -y pkg-config
          sudo apt-get install -y libssl-dev libcurl4-openssl-dev liblog4cplus-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-base-apps gstreamer1.0-plugins-bad gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-tools

          # Install git
          sudo apt-get install -y git

          # Clone the KVS SDK repository
          cd /home/ubuntu
          git clone https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp.git

          # Create directory for KVS SDK build and run build commands
          mkdir -p /home/ubuntu/amazon-kinesis-video-streams-producer-sdk-cpp/build
          cd /home/ubuntu/amazon-kinesis-video-streams-producer-sdk-cpp/build
          cmake .. -DBUILD_GSTREAMER_PLUGIN=ON -DBUILD_DEPENDENCIES=OFF -DALIGNED_MEMORY_MODEL=ON
          make

          # Set proper ownership
          chown -R ubuntu:ubuntu /home/ubuntu/amazon-kinesis-video-streams-producer-sdk-cpp

          # Install AWS CLI v2
          sudo apt-get install -y unzip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install

  # IAM Role and Instance Profile
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonKinesisVideoStreamsFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceId:
    Description: Instance ID of the created EC2 instance
    Value: !Ref EC2Instance
  PublicDNS:
    Description: Public DNS name of the created EC2 instance
    Value: !GetAtt EC2Instance.PublicDnsName
  PublicIP:
    Description: Public IP address of the created EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
  KeyPairName:
    Description: Name of the created key pair
    Value: !Ref EC2KeyPair
  KVSStreamName:
    Description: Name of the created KVS stream
    Value: !Ref KVSStream
  S3BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref S3Bucket